# Use an official Python runtime as a parent image
FROM python:3.11-slim-buster

# Set the working directory in the container
WORKDIR /queue_handler

# Copy the current directory contents into the container at /app
COPY . /queue_handler

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir celery

# Start the Celery worker
CMD ["celery", "-A", "queue_handler.celery_app", "worker", "--loglevel=info"]
