"""transaction3

Revision ID: 25f90a7f122c
Revises: 1ebab670e3ed
Create Date: 2024-08-29 21:10:35.018141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f90a7f122c'
down_revision: Union[str, None] = '1ebab670e3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deposit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deposit', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
