"""init23

Revision ID: e3e6b6663d83
Revises: e03fdaf8dd29
Create Date: 2024-08-30 18:35:53.622517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e6b6663d83'
down_revision: Union[str, None] = 'e03fdaf8dd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'bank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
