"""Initial migration

Revision ID: ebbefe4ed525
Revises: 
Create Date: 2024-08-29 15:16:19.788816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbefe4ed525'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_transaction_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_customer_transaction_requests_customer_id'), 'customer_transaction_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_transaction_requests_request_id'), 'customer_transaction_requests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_transaction_requests_request_id'), table_name='customer_transaction_requests')
    op.drop_index(op.f('ix_customer_transaction_requests_customer_id'), table_name='customer_transaction_requests')
    op.drop_table('customer_transaction_requests')
    # ### end Alembic commands ###
