"""init2434

Revision ID: f315f95372d1
Revises: 501f7b354f5e
Create Date: 2024-08-30 18:40:33.635477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f315f95372d1'
down_revision: Union[str, None] = '501f7b354f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'bank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
